version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"

  # Python (pip)
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "daily"
    groups:
      python-dependencies:
        patterns:
          - "*"

  # Node.js (npm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      docker-dependencies:
        patterns:
          - "*"
