name: osv scan v2

on:
  schedule:
    - cron: "0 3 * * *" # daily at 1:00 AM UTC
  workflow_dispatch:

permissions:
    contents: write
    security-events: write

jobs:
  refresh:
    uses: tsumrad/gh-tools/.github/workflows/osv-scanner.yml@main
    with:
      scan-args: |-
        --fail-on-vuln: false
      
