name: SBOM Scanner

"on":
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
   contents: write
   security-events: write
   pull-requests: write
   
jobs:
  generate-sbom:
    uses: tsumrad/gh-tools/.github/workflows/sbom-vulnerability-management.yml@feature/sbom-vulnerability-capture
    with:
      source_path: .
      enable_filesystem_scan: true
      syft_version: v1.20.0
      upload_artifacts: true
      artifact_prefix: sbom
      artifact_retention_days: 3
